# Exclude from ALL hooks
# Any file ending with .csv, .json, .ipynb, or in the .venv/, .git/, or .dvc/ directories.
exclude: '(\.csv|\.json|\.ipynb|\.venv/|\.git/|\.dvc/)$'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format